#!/bin/sh
set -e

# This script runs as part of the official Nginx entrypoint sequence.
# It checks for the existence of an .htpasswd file and creates the
# auth_basic.conf include file accordingly.

HTPASSWD_FILE="/etc/nginx/secrets/.htpasswd"
AUTH_CONF_FILE="/etc/nginx/auth_basic.conf"

if [ -s "$HTPASSWD_FILE" ]; then
  echo "✅ .htpasswd found. Enabling basic authentication."
  cat <<EOF > "$AUTH_CONF_FILE"
# This file is auto-generated by 40-conditional-auth.sh
auth_basic "Restricted Content";
auth_basic_user_file $HTPASSWD_FILE;
EOF
else
  echo "⚠️ .htpasswd not found. Disabling basic authentication."
  # Create an empty file. Nginx will ignore an empty include.
  touch "$AUTH_CONF_FILE"
fi
